//! Acceptance of the «Video» pipeline (T672–T679) on a real film, against a real server in a
//! container, through the very commands the screen calls (`video_add` → `video_set_audio` →
//! `video_start` …) — with a REAL measurement, not a loan and not the formula.
//!
//! **What «a real film» is here.** Generated by the bundled FFmpeg, but not a toy: 80 seconds of
//! 1920×1080 at 30 frames a second, moving picture with noise that grows in two steps (so the
//! light, middling and heavy chunks of the measurement are different material), TWO audio
//! tracks in different languages and different tones (eng 440 Hz at 48 kHz, rus 1000 Hz at
//! 44.1 kHz), a subtitle track and two chapters — the things a real release carries and a
//! synthetic 15-second clip does not.
//!
//! **What is printed.** Every test prints a block starting with `ACCEPTANCE` — the times of
//! the stages and the plan against the fact — for the report. Nothing in it is a threshold;
//! an error of more than twice is a finding to be reported, not a failure here.
//!
//! One server per test, one test at a time (`--test-threads=1`), each under 590 s on the
//! owner's machine (RTX 5080, `h264_nvenc`).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use vrcast_studio_lib::commands::video::{api as video, PlanSource, VideoView};
use vrcast_studio_lib::commands::{AppEvent, AppState};
use vrcast_studio_lib::domain::ladder::{Quality, Rung};
use vrcast_studio_lib::domain::video::{VideoStage, VideoState};
use vrcast_studio_lib::media::ffmpeg;
use vrcast_studio_lib::store::db::Db;
use vrcast_studio_lib::store::secrets::{InMemorySecretStore, SecretStore};
use vrcast_studio_lib::tasks::state::Lane;

use super::fixture::TestServer;
use super::upload_live::{add_profile, attach_secret};

const VIDEO_DIR: &str = "/var/lib/vrcast/videos";

/// The film's length. Long enough that the guards of the chunk choice are dropped and the
/// three chunks land on the three kinds of material; short enough that the whole way fits.
const FILM_S: u32 = 80;

/// The second audio track — the one chosen — and what it sounds like.
const CHOSEN_TRACK: usize = 1;
const CHOSEN_HZ: f64 = 1000.0;
const OTHER_HZ: f64 = 440.0;

// ---------- the film ----------

fn tool(name: &str) -> PathBuf {
    ffmpeg::locate(name).expect("no bundled FFmpeg: run `npm run ffmpeg`")
}

/// A real film: picture with motion and growing noise, two audio tracks, subtitles, chapters.
fn make_film(path: &Path, size: &str, seconds: u32) {
    let dir = path.parent().unwrap();
    let srt = dir.join(format!(
        "{}.srt",
        path.file_stem().unwrap().to_string_lossy()
    ));
    std::fs::write(
        &srt,
        "1\n00:00:01,000 --> 00:00:04,000\nHello\n\n2\n00:00:40,000 --> 00:00:44,000\nWorld\n",
    )
    .unwrap();
    let chapters = dir.join(format!(
        "{}.chapters.txt",
        path.file_stem().unwrap().to_string_lossy()
    ));
    let half = seconds * 1000 / 2;
    std::fs::write(
        &chapters,
        format!(
            ";FFMETADATA1\n[CHAPTER]\nTIMEBASE=1/1000\nSTART=0\nEND={half}\ntitle=Calm\n\
             [CHAPTER]\nTIMEBASE=1/1000\nSTART={half}\nEND={}\ntitle=Storm\n",
            seconds * 1000
        ),
    )
    .unwrap();
    // Three kinds of material: clean for the first third, light noise, then heavy noise.
    let third = seconds / 3;
    let picture = format!(
        "testsrc2=s={size}:r=30:d={seconds},\
         noise=alls=6:allf=t+u:enable='between(t,{third},{})',\
         noise=alls=18:allf=t+u:enable='gte(t,{})'",
        2 * third,
        2 * third
    );
    let out = std::process::Command::new(tool("ffmpeg"))
        .args([
            "-nostdin", "-y", "-v", "error", "-f", "lavfi", "-i", &picture,
        ])
        .args(["-f", "lavfi", "-i"])
        .arg(format!("sine=f={OTHER_HZ}:r=48000:d={seconds}"))
        .args(["-f", "lavfi", "-i"])
        .arg(format!("sine=f={CHOSEN_HZ}:r=44100:d={seconds}"))
        .arg("-i")
        .arg(&srt)
        .arg("-i")
        .arg(&chapters)
        .args([
            "-map",
            "0:v",
            "-map",
            "1:a",
            "-map",
            "2:a",
            "-map",
            "3:s",
            "-map_chapters",
            "4",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "21",
            "-g",
            "60",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-c:s",
            "srt",
            "-metadata:s:a:0",
            "language=eng",
            "-metadata:s:a:0",
            "title=English",
            "-metadata:s:a:1",
            "language=rus",
            "-metadata:s:a:1",
            "title=Russian",
            "-metadata:s:s:0",
            "language=eng",
        ])
        .arg(path)
        .output()
        .expect("could not run the bundled FFmpeg");
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

/// A directory that removes itself.
struct Scratch(PathBuf);

impl Scratch {
    fn new(what: &str) -> Self {
        let dir = std::env::temp_dir().join(format!(
            "vrcast-accept-{what}-{}",
            uuid::Uuid::new_v4().simple()
        ));
        std::fs::create_dir_all(&dir).expect("could not make a working directory");
        Self(dir)
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

// ---------- the application ----------

fn origin_of(server: &TestServer) -> String {
    format!("http://{}:{}", server.host(), server.http_port)
}

fn state_on(db: &Path, secrets: Arc<dyn SecretStore>, origin: &str) -> AppState {
    let mut state = AppState::with_db(
        Arc::new(Db::open(db).expect("the database would not open")),
        secrets,
    )
    .expect("the application state would not assemble");
    state.verify_origin = Some(origin.to_owned());
    state
}

async fn until(
    state: &AppState,
    id: &str,
    what: &str,
    limit: Duration,
    ok: impl Fn(&VideoView) -> bool,
) -> VideoView {
    let deadline = Instant::now() + limit;
    loop {
        let now = video::video_get(state, id).expect("the video went missing");
        if ok(&now) {
            return now;
        }
        assert!(
            Instant::now() < deadline,
            "{what}: never got there; the video is {:?} at {:?}, problem {:?}",
            now.state,
            now.stage,
            now.problem
        );
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
}

fn finished(v: &VideoView) -> bool {
    matches!(
        v.state,
        VideoState::Done | VideoState::Problem | VideoState::Cancelled
    )
}

/// Every `video:update`, as the screen receives it, with the moment it came.
#[derive(Clone, Default)]
struct Recorder {
    seen: Arc<Mutex<Vec<(Instant, VideoView)>>>,
    lagged: Arc<Mutex<u64>>,
}

impl Recorder {
    /// Listen from now on. Drained in a task of its own so the channel (64 deep) never fills.
    fn start(state: &AppState) -> Self {
        let rec = Self::default();
        let mut rx = state.subscribe();
        let r = rec.clone();
        tokio::spawn(async move {
            loop {
                match rx.recv().await {
                    Ok(AppEvent::VideoUpdate(v)) => {
                        r.seen.lock().unwrap().push((Instant::now(), *v));
                    }
                    Ok(_) => {}
                    Err(tokio::sync::broadcast::error::RecvError::Lagged(n)) => {
                        *r.lagged.lock().unwrap() += n;
                    }
                    Err(tokio::sync::broadcast::error::RecvError::Closed) => return,
                }
            }
        });
        rec
    }

    fn of(&self, id: &str) -> Vec<(Instant, VideoView)> {
        self.seen
            .lock()
            .unwrap()
            .iter()
            .filter(|(_, v)| v.id == id)
            .cloned()
            .collect()
    }
}

/// The stage order with encoding and sending taken as one (they alternate rung by rung).
fn rank(s: VideoStage) -> VideoStage {
    match s {
        VideoStage::Uploading => VideoStage::Encoding,
        other => other,
    }
}

/// What the events say, checked: the order of the stages, the bars, the figures.
struct Timeline {
    /// The stages in the order shown, consecutive repeats folded.
    stages: Vec<VideoStage>,
    /// Seconds spent in each stage (the sum of its stretches).
    spent: BTreeMap<&'static str, f64>,
    /// Bars that went backwards within one stage of one rung: (stage, rung, from, to).
    backwards: Vec<(VideoStage, Option<u32>, f64, f64)>,
    out_of_range: Vec<f64>,
    eta_while: Vec<VideoStage>,
    speed_while: Vec<VideoStage>,
    events: usize,
}

fn read_timeline(events: &[(Instant, VideoView)]) -> Timeline {
    let mut stages: Vec<VideoStage> = Vec::new();
    let mut spent: BTreeMap<&'static str, f64> = BTreeMap::new();
    let mut backwards = Vec::new();
    let mut out_of_range = Vec::new();
    let mut eta_while = Vec::new();
    let mut speed_while = Vec::new();
    let mut last: Option<(Instant, VideoStage)> = None;
    let mut bar: Option<(VideoStage, Option<u32>, f64)> = None;
    for (at, v) in events {
        if let Some((since, stage)) = last {
            *spent.entry(stage.as_str()).or_default() += at.duration_since(since).as_secs_f64();
        }
        last = Some((*at, v.stage));
        if stages.last() != Some(&v.stage) {
            stages.push(v.stage);
        }
        if v.state != VideoState::Working {
            continue;
        }
        let Some(p) = &v.progress else { continue };
        if !(0.0..=1.0).contains(&p.progress) {
            out_of_range.push(p.progress);
        }
        if p.eta_s.is_some() && !eta_while.contains(&v.stage) {
            eta_while.push(v.stage);
        }
        if p.speed_bps.is_some() && !speed_while.contains(&v.stage) {
            speed_while.push(v.stage);
        }
        if let Some((stage, rung, was)) = bar {
            if stage == v.stage && rung == p.rung && p.progress + 1e-9 < was {
                backwards.push((stage, rung, was, p.progress));
            }
        }
        bar = Some((v.stage, p.rung, p.progress));
    }
    Timeline {
        stages,
        spent,
        backwards,
        out_of_range,
        eta_while,
        speed_while,
        events: events.len(),
    }
}

/// The stages go forward only, apart from encoding ⇄ sending, and none from `from` on is
/// skipped.
fn assert_stage_order(t: &Timeline, from: VideoStage) {
    for pair in t.stages.windows(2) {
        assert!(
            rank(pair[0]) <= rank(pair[1]),
            "the stage went back: {:?}",
            t.stages
        );
    }
    for wanted in VideoStage::ALL.iter().filter(|s| **s >= from) {
        assert!(
            t.stages.contains(wanted),
            "{wanted:?} was never shown: {:?}",
            t.stages
        );
    }
}

// ---------- the server ----------

fn http_get(url: &str) -> (u16, String) {
    // The bundled FFmpeg has no plain HTTP fetcher; curl comes with Windows 10+ and Linux.
    let out = std::process::Command::new("curl")
        .args(["-s", "-o", "-", "-w", "\n%{http_code}", url])
        .output()
        .expect("curl did not run");
    let text = String::from_utf8_lossy(&out.stdout).into_owned();
    let (body, code) = text.rsplit_once('\n').unwrap_or(("", "0"));
    (code.trim().parse().unwrap_or(0), body.to_owned())
}

/// The variant playlists a master names, in its order.
fn variants_of(master: &str) -> Vec<String> {
    master
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(str::to_owned)
        .collect()
}

/// Decode the whole of `url` and return how long it is, in seconds, and what FFmpeg said.
fn decode_whole(url: &str) -> (f64, String) {
    let out = std::process::Command::new(tool("ffmpeg"))
        .args([
            "-nostdin",
            "-v",
            "error",
            "-xerror",
            "-i",
            url,
            "-f",
            "null",
            "-progress",
            "pipe:1",
            "-",
        ])
        .output()
        .expect("ffmpeg did not run");
    let said = String::from_utf8_lossy(&out.stderr).into_owned();
    assert!(out.status.success(), "{url} would not decode whole: {said}");
    let us = String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter_map(|l| l.strip_prefix("out_time_us="))
        .filter_map(|v| v.trim().parse::<i64>().ok())
        .max()
        .unwrap_or(0);
    (us as f64 / 1e6, said)
}

/// What the audio of `url` sounds like: its frequency by zero crossings, over 5 seconds from
/// the 10th, and the sample rate the stream declares.
fn audio_of(url: &str) -> (f64, String) {
    let out = std::process::Command::new(tool("ffmpeg"))
        .args([
            "-nostdin", "-v", "error", "-ss", "10", "-t", "5", "-i", url, "-map", "0:a:0", "-ac",
            "1", "-ar", "48000", "-f", "s16le", "-",
        ])
        .output()
        .expect("ffmpeg did not run");
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let samples: Vec<i16> = out
        .stdout
        .chunks_exact(2)
        .map(|b| i16::from_le_bytes([b[0], b[1]]))
        .collect();
    let crossings = samples
        .windows(2)
        .filter(|w| (w[0] < 0) != (w[1] < 0))
        .count();
    let hz = crossings as f64 / 2.0 / (samples.len() as f64 / 48_000.0);
    let probe = std::process::Command::new(tool("ffprobe"))
        .args([
            "-v",
            "error",
            "-select_streams",
            "a",
            "-show_entries",
            "stream=sample_rate:stream_tags=language",
            "-of",
            "compact=p=0:nk=1",
            url,
        ])
        .output()
        .expect("ffprobe did not run");
    (hz, String::from_utf8_lossy(&probe.stdout).trim().to_owned())
}

/// What the set takes on the server, in bytes: its prepared rungs and its directory.
fn bytes_on_server(server: &TestServer, slug: &str) -> u64 {
    server
        .exec_inside(&format!(
            "cd '{VIDEO_DIR}' && du -cb {slug}_*.mp4 '{slug}' | tail -1 | cut -f1"
        ))
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0)
}

fn ls_server(server: &TestServer) -> String {
    server
        .exec_inside(&format!("cd '{VIDEO_DIR}' && find . | sort"))
        .unwrap_or_default()
}

// ---------- the processes ----------

/// FFmpeg and FFprobe processes whose parent is this test process (Windows) — what a cancel
/// must leave none of.
fn our_encoders() -> Vec<String> {
    let me = std::process::id();
    if cfg!(windows) {
        let out = std::process::Command::new("powershell")
            .args([
                "-NoProfile",
                "-Command",
                &format!(
                    "Get-CimInstance Win32_Process -Filter \"ParentProcessId={me}\" | \
                     Where-Object {{ $_.Name -match 'ffmpeg|ffprobe' }} | \
                     ForEach-Object {{ \"$($_.ProcessId) $($_.Name)\" }}"
                ),
            ])
            .output()
            .expect("powershell did not run");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(|l| l.trim().to_owned())
            .filter(|l| !l.is_empty())
            .collect()
    } else {
        let out = std::process::Command::new("pgrep")
            .args(["-P", &me.to_string(), "-l", "ffmpeg|ffprobe"])
            .output()
            .expect("pgrep did not run");
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(str::to_owned)
            .collect()
    }
}

/// Every file left under a directory, recursively.
fn files_under(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                out.extend(files_under(&p));
            } else {
                out.push(p);
            }
        }
    }
    out
}

// ---------- 1. the whole way ----------

/// Add, choose the second audio track, «Start»: a real measurement, the rungs, the cutting,
/// the check, the link. Every `video:update` is recorded and checked; every rung is asked for
/// over HTTP through the master, decoded whole, and listened to.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn a_real_film_goes_the_whole_way_with_a_real_measurement_on_the_second_audio_track() {
    super::fixture::logging_if_requested();
    let server = TestServer::start().expect("the container would not come up");
    let scratch = Scratch::new("whole");
    let state = state_on(
        &scratch.0.join("vrcast.sqlite3"),
        Arc::new(InMemorySecretStore::new()),
        &origin_of(&server),
    );
    let server_id = add_profile(&state, &server).await;
    let film = scratch.0.join("Real Film.mkv");
    let made = Instant::now();
    make_film(&film, "1920x1080", FILM_S);
    let film_bytes = std::fs::metadata(&film).unwrap().len();
    eprintln!(
        "ACCEPTANCE film: {} bytes ({:.1} Mbit/s), made in {:.1}s",
        film_bytes,
        film_bytes as f64 * 8.0 / FILM_S as f64 / 1e6,
        made.elapsed().as_secs_f64()
    );

    let rec = Recorder::start(&state);
    let added = video::video_add(
        &state,
        &server_id,
        &[film.to_string_lossy().into_owned()],
        None,
    )
    .await
    .expect("adding failed");
    assert!(added.refused.is_empty(), "{:?}", added.refused);
    let id = added.added[0].id.clone();

    let ready = until(&state, &id, "the plan", Duration::from_secs(120), |v| {
        v.state != VideoState::Planning
    })
    .await;
    assert_eq!(ready.state, VideoState::Ready, "{:?}", ready.problem);
    let source = ready.source.clone().expect("no source");
    assert_eq!(source.audio_tracks.len(), 2, "{:?}", source.audio_tracks);
    let plan_before = ready.plan.clone().expect("no plan");
    assert_eq!(plan_before.from, PlanSource::Formula);
    assert!(plan_before.needs_measuring);

    // The second track, chosen the way the screen chooses it.
    let chosen = video::video_set_audio(&state, &id, CHOSEN_TRACK).expect("the track was refused");
    assert_eq!(chosen.audio_track, CHOSEN_TRACK);
    let plan_at_start = chosen.plan.clone().unwrap();

    let started_at = Instant::now();
    let started = video::video_start(&state, std::slice::from_ref(&id));
    assert!(started[0].error.is_none(), "{:?}", started[0].error);

    let done = until(
        &state,
        &id,
        "the whole way",
        Duration::from_secs(560),
        finished,
    )
    .await;
    let took = started_at.elapsed().as_secs_f64();
    assert_eq!(done.state, VideoState::Done, "{:?}", done.problem);
    tokio::time::sleep(Duration::from_millis(300)).await;

    // ---- the events ----
    let events = rec.of(&id);
    let t = read_timeline(&events);
    eprintln!(
        "ACCEPTANCE whole-way: {} events (lagged {}), stages {:?}",
        t.events,
        rec.lagged.lock().unwrap(),
        t.stages
    );
    eprintln!("ACCEPTANCE whole-way: seconds per stage {:?}", t.spent);
    eprintln!(
        "ACCEPTANCE whole-way: eta seen in {:?}, speed seen in {:?}",
        t.eta_while, t.speed_while
    );
    eprintln!(
        "ACCEPTANCE whole-way: bars that went back {} {:?}",
        t.backwards.len(),
        t.backwards.iter().take(12).collect::<Vec<_>>()
    );
    assert_stage_order(&t, VideoStage::Planned);
    assert!(t.out_of_range.is_empty(), "{:?}", t.out_of_range);
    assert!(
        t.eta_while.contains(&VideoStage::Encoding),
        "no time left was ever shown while encoding"
    );
    assert!(
        t.speed_while.contains(&VideoStage::Uploading)
            && t.eta_while.contains(&VideoStage::Uploading),
        "no speed or time left while sending: speed {:?} eta {:?}",
        t.speed_while,
        t.eta_while
    );
    assert_eq!(*rec.lagged.lock().unwrap(), 0, "events were dropped");
    let backwards = t.backwards.clone();

    // ---- the set, as a viewer gets it ----
    let link = done.link.clone().expect("a finished video has no link");
    let master_path = format!("/videos/{}/master.m3u8", done.slug);
    assert!(link.origin.ends_with(&master_path), "{}", link.origin);
    let master_url = format!("{}{master_path}", origin_of(&server));
    let (code, master) = http_get(&master_url);
    assert_eq!(code, 200, "{master_url}");
    let variants = variants_of(&master);
    let rungs = done.plan.as_ref().unwrap().rungs.clone();
    assert_eq!(done.plan.as_ref().unwrap().from, PlanSource::Measured);
    assert_eq!(variants.len(), rungs.len(), "{master}");
    assert!(
        rungs.len() >= 2,
        "the measurement chose one rung: {rungs:?}"
    );
    for v in &variants {
        let url = format!("{}/videos/{}/{v}", origin_of(&server), done.slug);
        let (length, said) = decode_whole(&url);
        let (hz, declared) = audio_of(&url);
        eprintln!(
            "ACCEPTANCE rung {v}: {length:.2}s decoded, audio {hz:.0} Hz, declared [{declared}], ffmpeg said {:?}",
            said.lines().take(3).collect::<Vec<_>>()
        );
        assert!(
            (length - FILM_S as f64).abs() <= 1.0,
            "{v} is {length:.2}s, the film is {FILM_S}s"
        );
        assert!(
            (hz - CHOSEN_HZ).abs() < 50.0,
            "{v} sounds at {hz:.0} Hz — not the chosen track ({CHOSEN_HZ} Hz; the other is {OTHER_HZ} Hz)"
        );
    }
    // The prepared rung files keep the language of the chosen track.
    let langs = server
        .exec_inside(&format!(
            "cd '{VIDEO_DIR}' && for f in {}_*.mp4; do echo \"$f $(ffprobe -v error -select_streams a -show_entries stream=sample_rate:stream_tags=language -of compact=p=0:nk=1 \"$f\")\"; done",
            done.slug
        ))
        .unwrap_or_default();
    eprintln!("ACCEPTANCE prepared rungs' audio: {langs:?}");

    // ---- plan against fact ----
    let measured_plan = done.plan.clone().unwrap();
    let on_server = bytes_on_server(&server, &done.slug);
    let encode_fact = t.spent.get("encoding").copied().unwrap_or(0.0);
    let measure_fact = t.spent.get("measuring").copied().unwrap_or(0.0);
    eprintln!(
        "ACCEPTANCE plan-vs-fact: rungs {:?}",
        rungs
            .iter()
            .map(|r| format!("{}p@{:.2}Mb", r.height, r.bitrate_bps as f64 / 1e6))
            .collect::<Vec<_>>()
    );
    eprintln!(
        "ACCEPTANCE plan-vs-fact: server bytes — formula plan {} / measured plan {} / fact {} (fact/measured {:.2})",
        plan_at_start.server_bytes,
        measured_plan.server_bytes,
        on_server,
        on_server as f64 / measured_plan.server_bytes.max(1) as f64
    );
    eprintln!(
        "ACCEPTANCE plan-vs-fact: measuring — plan {}s / fact {measure_fact:.0}s; encoding — plan {:?}s ({:?}) / fact {encode_fact:.0}s; total {took:.0}s",
        plan_at_start.measure_s, plan_at_start.encode_s, plan_at_start.encode_estimate
    );
    eprintln!(
        "ACCEPTANCE plan-vs-fact: local bytes plan {} ; encoder {}",
        measured_plan.local_bytes, measured_plan.encoder
    );

    // The work folder beside the film is empty again.
    let left = files_under(&scratch.0.join("vrcast-work"));
    assert!(left.is_empty(), "left in the working folder: {left:?}");

    // ---- the library: the medium with its set and the set's rung files ----
    let view = vrcast_studio_lib::commands::library::api::library_list(&state, &server_id, true)
        .await
        .unwrap();
    let m = view
        .media
        .iter()
        .find(|m| Some(&m.id) == done.media_id.as_ref())
        .expect("the medium is not in the library");
    assert!(
        m.ladders
            .iter()
            .any(|l| l.path == format!("{}/master.m3u8", done.slug)),
        "{m:?}"
    );
    assert_eq!(m.set_files.len(), rungs.len(), "{m:?}");
    assert!(view.unrecognized.is_empty(), "{:?}", view.unrecognized);

    // Checked last so that every number above is printed for the report first.
    assert!(
        backwards.is_empty(),
        "the bar went back within a stage of one rung: {backwards:?}"
    );
}

// ---------- 2. killed while measuring ----------

mod env_names {
    pub const DB: &str = "VRCAST_ACCEPT_DB";
    pub const FILM: &str = "VRCAST_ACCEPT_FILM";
    pub const ORIGIN: &str = "VRCAST_ACCEPT_ORIGIN";
    pub const MARK: &str = "VRCAST_ACCEPT_MARK";
}

const HELPER: &str = "video_acceptance::the_first_run_that_is_killed_while_measuring";

/// The first run — the one killed while measuring. Not a check on its own: started only by
/// the check below, as a process of its own. With no conditions in the environment it does
/// nothing.
#[test]
#[ignore = "half of the kill-while-measuring check: started as a process of its own"]
fn the_first_run_that_is_killed_while_measuring() {
    let (Ok(db), Ok(film), Ok(origin), Ok(mark)) = (
        std::env::var(env_names::DB),
        std::env::var(env_names::FILM),
        std::env::var(env_names::ORIGIN),
        std::env::var(env_names::MARK),
    ) else {
        return;
    };
    let rt = tokio::runtime::Runtime::new().expect("the runtime would not be created");
    rt.block_on(async move {
        let state = state_on(
            Path::new(&db),
            Arc::new(InMemorySecretStore::new()),
            &origin,
        );
        let server_id = attach_secret(&state);
        let added = video::video_add(&state, &server_id, &[film], None)
            .await
            .unwrap();
        let id = added.added[0].id.clone();
        until(&state, &id, "the plan", Duration::from_secs(120), |v| {
            v.state == VideoState::Ready
        })
        .await;
        video::video_set_audio(&state, &id, CHOSEN_TRACK).unwrap();
        let started = video::video_start(&state, std::slice::from_ref(&id));
        assert!(started[0].error.is_none(), "{:?}", started[0].error);
        std::fs::write(&mark, &id).unwrap();
        loop {
            tokio::time::sleep(Duration::from_secs(3600)).await;
        }
    });
}

struct Killable(std::process::Child);

impl Drop for Killable {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}

/// The measured points as the database holds them: (bitrate, height) → when measured.
fn points_in(db: &Path) -> BTreeMap<(i64, i64), String> {
    let Ok(c) = rusqlite::Connection::open_with_flags(
        db,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY | rusqlite::OpenFlags::SQLITE_OPEN_NO_MUTEX,
    ) else {
        return BTreeMap::new();
    };
    let Ok(mut q) = c.prepare("SELECT bitrate_mbps, height, measured_at FROM quality_points")
    else {
        return BTreeMap::new();
    };
    q.query_map([], |r| Ok(((r.get(0)?, r.get(1)?), r.get(2)?)))
        .map(|rows| rows.flatten().collect())
        .unwrap_or_default()
}

/// Killed while measuring, after some points and before the last: after a restart the video
/// carries on measuring by itself, the points already taken are not taken again, and it gets
/// to «done».
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn killed_while_measuring_it_carries_on_measuring_without_measuring_again_and_gets_done() {
    super::fixture::logging_if_requested();
    let server = TestServer::start().expect("the container would not come up");
    let scratch = Scratch::new("kill-measure");
    let db = scratch.0.join("vrcast.sqlite3");
    let secrets: Arc<dyn SecretStore> = Arc::new(InMemorySecretStore::new());
    {
        let state = state_on(&db, secrets.clone(), &origin_of(&server));
        add_profile(&state, &server).await;
    }
    let film = scratch.0.join("Killed While Measuring.mkv");
    make_film(&film, "1920x1080", FILM_S);
    let mark = scratch.0.join("started");

    let child = std::process::Command::new(std::env::current_exe().unwrap())
        .args([HELPER, "--exact", "--ignored", "--test-threads=1"])
        .env(env_names::DB, &db)
        .env(env_names::FILM, &film)
        .env(env_names::ORIGIN, origin_of(&server))
        .env(env_names::MARK, &mark)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .expect("the first run did not start");
    let child_pid = child.id();
    let mut running = Killable(child);

    // Some points down, the measurement still going.
    let deadline = Instant::now() + Duration::from_secs(300);
    let before = loop {
        let points = points_in(&db);
        if points.len() >= 3 && mark.exists() {
            break points;
        }
        if let Ok(Some(status)) = running.0.try_wait() {
            panic!("the first run ended by itself ({status})");
        }
        assert!(Instant::now() < deadline, "no point was ever measured");
        std::thread::sleep(Duration::from_millis(200));
    };
    // The killed run's own encoders, as they are the moment before it dies: killing the test
    // process does not take them, and the next start's sweep (T504) is what has to.
    let orphans: Vec<String> = {
        let out = std::process::Command::new("powershell")
            .args([
                "-NoProfile",
                "-Command",
                &format!(
                    "Get-CimInstance Win32_Process -Filter \"ParentProcessId={child_pid}\" | \
                     Where-Object {{ $_.Name -match 'ffmpeg|ffprobe' }} | \
                     ForEach-Object {{ \"$($_.ProcessId) $($_.Name)\" }}"
                ),
            ])
            .output()
            .unwrap();
        String::from_utf8_lossy(&out.stdout)
            .lines()
            .map(|l| l.trim().to_owned())
            .filter(|l| !l.is_empty())
            .collect()
    };
    let killed_at = Instant::now();
    drop(running);
    let id = std::fs::read_to_string(&mark).unwrap();

    // The application starts again — nobody presses anything.
    let state = state_on(&db, secrets.clone(), &origin_of(&server));
    attach_secret(&state);
    let at_restart = video::video_get(&state, &id).unwrap();
    assert_eq!(at_restart.state, VideoState::Working);
    assert_eq!(at_restart.stage, VideoStage::Measuring, "{at_restart:?}");
    let rec = Recorder::start(&state);
    assert_eq!(video::restore_videos(&state).unwrap(), 1);

    let done = until(
        &state,
        &id,
        "carrying on",
        Duration::from_secs(480),
        finished,
    )
    .await;
    assert_eq!(done.state, VideoState::Done, "{:?}", done.problem);
    let after = points_in(&db);

    let remeasured: Vec<_> = before
        .iter()
        .filter(|(cell, at)| after.get(*cell) != Some(*at))
        .collect();
    let t = read_timeline(&rec.of(&id));
    eprintln!(
        "ACCEPTANCE kill-measuring: {} points before the kill, {} after; re-measured {:?}; \
         encoders of the killed run at the kill {:?}; stages after restart {:?}; \
         restart→done {:.0}s",
        before.len(),
        after.len(),
        remeasured,
        orphans,
        t.stages,
        killed_at.elapsed().as_secs_f64()
    );
    assert!(
        remeasured.is_empty(),
        "points were measured again: {remeasured:?}"
    );
    assert!(
        after.len() > before.len(),
        "nothing was measured after the restart"
    );
    assert_eq!(
        t.stages.first(),
        Some(&VideoStage::Measuring),
        "{:?}",
        t.stages
    );
    assert_stage_order(&t, VideoStage::Measuring);
    assert_eq!(done.plan.unwrap().from, PlanSource::Measured);
    let (code, _) = http_get(&format!(
        "{}/videos/{}/master.m3u8",
        origin_of(&server),
        done.slug
    ));
    assert_eq!(code, 200);
    // The killed run's FFmpeg is not left running: by now the sweep or its own end took it.
    let still: Vec<&String> = orphans
        .iter()
        .filter(|o| {
            o.split_whitespace()
                .next()
                .and_then(|p| p.parse::<u32>().ok())
                .is_some_and(super::proc_check::alive)
        })
        .collect();
    assert!(
        still.is_empty(),
        "the killed run's programs live on: {still:?}"
    );
}

// ---------- 3. two at once ----------

/// Two videos started together: the limit of heavy work (one per heavy lane by default) holds
/// all the way, and both get to «done».
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn two_videos_started_together_keep_to_the_limit_and_both_get_done() {
    super::fixture::logging_if_requested();
    let server = TestServer::start().expect("the container would not come up");
    let scratch = Scratch::new("two");
    let state = state_on(
        &scratch.0.join("vrcast.sqlite3"),
        Arc::new(InMemorySecretStore::new()),
        &origin_of(&server),
    );
    let server_id = add_profile(&state, &server).await;
    let limit = vrcast_studio_lib::store::settings::load(&state.db)
        .unwrap()
        .concurrent_heavy_tasks as usize;

    // Two films: 720p, a minute each — two real measurements must fit in one test.
    let a = scratch.0.join("First Of Two.mkv");
    let b = scratch.0.join("Second Of Two.mkv");
    make_film(&a, "1280x720", 60);
    make_film(&b, "1280x720", 60);
    let added = video::video_add(
        &state,
        &server_id,
        &[
            a.to_string_lossy().into_owned(),
            b.to_string_lossy().into_owned(),
        ],
        None,
    )
    .await
    .unwrap();
    assert!(added.refused.is_empty(), "{:?}", added.refused);
    let ids: Vec<String> = added.added.iter().map(|v| v.id.clone()).collect();
    for id in &ids {
        until(&state, id, "the plan", Duration::from_secs(120), |v| {
            v.state != VideoState::Planning
        })
        .await;
    }
    let started_at = Instant::now();
    let started = video::video_start(&state, &ids);
    assert!(started.iter().all(|s| s.error.is_none()), "{started:?}");

    let mut most = (0usize, 0usize, 0usize);
    let mut both_heavy_lanes_at_once = 0u32;
    let deadline = Instant::now() + Duration::from_secs(560);
    loop {
        let compute = state.tasks.running_in_lane(Lane::Compute);
        let network = state.tasks.running_in_lane(Lane::Network);
        most.0 = most.0.max(compute);
        most.1 = most.1.max(network);
        most.2 = most.2.max(compute + network);
        if compute > 0 && network > 0 {
            both_heavy_lanes_at_once += 1;
        }
        assert!(
            compute <= limit && network <= limit,
            "over the limit {limit}: compute {compute}, network {network}"
        );
        let views: Vec<VideoView> = ids
            .iter()
            .map(|id| video::video_get(&state, id).unwrap())
            .collect();
        if views.iter().all(finished) {
            for v in &views {
                assert_eq!(v.state, VideoState::Done, "{} {:?}", v.title, v.problem);
                let (code, _) = http_get(&format!(
                    "{}/videos/{}/master.m3u8",
                    origin_of(&server),
                    v.slug
                ));
                assert_eq!(code, 200, "{}", v.slug);
            }
            break;
        }
        assert!(Instant::now() < deadline, "not both done: {views:?}");
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    eprintln!(
        "ACCEPTANCE two-at-once: limit {limit}; most at once — compute {}, network {}, both lanes {}; \
         samples with a measurement and a build running together {both_heavy_lanes_at_once}; \
         both done in {:.0}s",
        most.0,
        most.1,
        most.2,
        started_at.elapsed().as_secs_f64()
    );
}

// ---------- 4. cancelled while encoding ----------

/// Three rungs measured here — the rung editor's way, so the cancel lands in encoding without
/// a measurement first.
fn three_rungs() -> Vec<Rung> {
    let rung = |index, bitrate_bps: u64, width, height, vmaf| Rung {
        index,
        bitrate_bps,
        maxrate_bps: bitrate_bps + bitrate_bps / 10,
        bufsize_bps: bitrate_bps + bitrate_bps / 10,
        width,
        height,
        level: String::from("4.1"),
        reasons: Vec::new(),
        quality: Quality::MeasuredHere { vmaf_x100: vmaf },
    };
    vec![
        rung(0, 8_000_000, 1920, 1080, 9500),
        rung(1, 4_000_000, 1280, 720, 9300),
        rung(2, 1_500_000, 854, 480, 9000),
    ]
}

/// «Stop» while the second rung is being encoded: `cancelled`, no FFmpeg left, nothing
/// half-made here, no half set served on the server — and «Retry» finishes it without sending
/// the first rung again.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn cancelled_while_encoding_leaves_no_program_no_part_and_no_half_set() {
    super::fixture::logging_if_requested();
    let server = TestServer::start().expect("the container would not come up");
    let scratch = Scratch::new("cancel");
    let state = state_on(
        &scratch.0.join("vrcast.sqlite3"),
        Arc::new(InMemorySecretStore::new()),
        &origin_of(&server),
    );
    let server_id = add_profile(&state, &server).await;
    let film = scratch.0.join("Cancelled.mkv");
    make_film(&film, "1920x1080", FILM_S);
    let added = video::video_add(
        &state,
        &server_id,
        &[film.to_string_lossy().into_owned()],
        None,
    )
    .await
    .unwrap();
    let id = added.added[0].id.clone();
    until(&state, &id, "the plan", Duration::from_secs(120), |v| {
        v.state == VideoState::Ready
    })
    .await;
    video::video_set_audio(&state, &id, CHOSEN_TRACK).unwrap();
    video::video_set_rungs(&state, &id, Some(three_rungs())).unwrap();
    let rec = Recorder::start(&state);
    video::video_start(&state, std::slice::from_ref(&id));

    // The second rung, being encoded, partway.
    let at = until(
        &state,
        &id,
        "the second rung",
        Duration::from_secs(300),
        |v| {
            v.stage == VideoStage::Encoding
                && v.progress
                    .as_ref()
                    .is_some_and(|p| p.rung == Some(2) && p.progress > 0.2)
        },
    )
    .await;
    let slug = at.slug.clone();
    let first_rung = server
        .exec_inside(&format!("stat -c '%i %s %Y' '{VIDEO_DIR}/{slug}_8.mp4'"))
        .ok();
    let encoders_before = our_encoders();
    let pressed = Instant::now();
    let answer = video::video_cancel(&state, &id).expect("stop was refused");
    let cancelled = until(&state, &id, "cancelled", Duration::from_secs(60), |v| {
        v.state == VideoState::Cancelled
    })
    .await;
    let stop_took = pressed.elapsed().as_secs_f64();
    tokio::time::sleep(Duration::from_millis(500)).await;

    let encoders_after = our_encoders();
    let local_left = files_under(&scratch.0.join("vrcast-work"));
    let server_now = ls_server(&server);
    eprintln!(
        "ACCEPTANCE cancel: answered {:?}, cancelled in {stop_took:.1}s at {:?}; encoders before {:?} after {:?}; \
         local left {:?}; server:\n{server_now}",
        answer.state, cancelled.stage, encoders_before, encoders_after, local_left
    );
    assert!(
        !encoders_before.is_empty(),
        "no encoder was running when stop was pressed"
    );
    assert!(
        encoders_after.is_empty(),
        "left running: {encoders_after:?}"
    );
    assert!(local_left.is_empty(), "left here: {local_left:?}");
    assert!(
        !server_now.contains(".part"),
        "a staged file is left on the server:\n{server_now}"
    );
    assert!(
        !server_now.contains(&format!("./{slug}/master.m3u8")),
        "a master is served for a set that was stopped:\n{server_now}"
    );
    let (code, _) = http_get(&format!("{}/videos/{slug}/master.m3u8", origin_of(&server)));
    assert_ne!(code, 200, "the stopped set is served");
    let t = read_timeline(&rec.of(&id));
    assert!(
        t.stages.iter().all(|s| *s <= VideoStage::Uploading),
        "{:?}",
        t.stages
    );

    // «Retry» carries on and finishes, finding the first rung on the server done.
    video::video_retry(&state, &id, false).expect("retry was refused");
    let done = until(
        &state,
        &id,
        "after retry",
        Duration::from_secs(300),
        finished,
    )
    .await;
    assert_eq!(done.state, VideoState::Done, "{:?}", done.problem);
    let first_after = server
        .exec_inside(&format!("stat -c '%i %s %Y' '{VIDEO_DIR}/{slug}_8.mp4'"))
        .ok();
    eprintln!("ACCEPTANCE cancel: first rung before {first_rung:?}, after retry {first_after:?}");
    assert!(
        first_rung.is_some(),
        "the first rung was not on the server when stopped"
    );
    assert_eq!(first_after, first_rung, "the first rung was sent again");
}
